### ISSUE TITLE
Support for locales[] filtering on get_coverart_list()

### ISSUE THREAD

**Issue by zachstultz** [EMACC99/mangadex#23]
Pulling down a cover art list can give you English covers, Japanese covers, Portuguese covers, and so on. An option to filter by a locale would be great as I'm currently unable to tell which belongs to which language.

https://api.mangadex.org/docs/redoc.html#tag/Cover/operation/get-cover

Example of manga with covers for multiple locales:
https://mangadex.org/title/e83c326b-921b-45ff-bc0c-d667bbfe64cc/kanojo-mo-kanojo?tab=art

**Comment by EMACC99** [comment]
Hi, thanks for bringing this up, I'm adding the locale attribute to the cover art and I'm going to implement a more general filtering method for example a `api.get_cover_art(cover_id).filter(by=locale)` style in order to filter at the moment of the request and not create unnecessary `CoverArt` objects and going to do it in a more general way for all the locales and translated languages in `Manga` and `Chapter` objects
