### ISSUE TITLE
filtering chapter list by TL language doesn't work

### ISSUE THREAD

**Issue by typhoon71** [EMACC99/mangadex#8]
**Describe the bug**
filtering chapter list by TL language doesn't work, you get a 400 response

**To Reproduce**
import mangadex

```python3
import mangadex

api = mangadex.Api()
chapter_list = api.chapter_list(manga="30196491-8fc2-4961-8886-a58f898b1b3e", chapter=35, limit=20, translatedLanguage='en')
```

**Expected behavior**
get only the chapter translated in ''en"

The call works fine till I add `translatedLanguage='en'`; "translatedLanguage" should be a valid parameter.
Passig `translatedLanguage=['en']` doesn't solve it (the is Array of strings, so I tried but no dice).

bw: awesome work, I wanted to do some mangadex-API to python3 myself, but this is just right for me.

**Comment by EMACC99** [comment]
I looked into it and discovered I was not parsing some parameters correctly, I just made some changes and saw that many other functions have this issue too. It was my bad for overlooking this issue but it should be fixed by now. I still need to create the release, but you can clone the repo and install it with setup.py if you want. Also if you encounter any other issues, please let me know.

**Comment by typhoon71** [comment]
Thanks a lot, I will test this as soon I get a bit of time, this weekend I suppose.

**Comment by typhoon71** [comment]
Played around a bit before going to bed and spotted something: I think "sacanlation_group_id" should be "scanlation_group_id", as it's in mangadex API.

More serious testing later as I said, but seems good to me.
